server:
  port: 8888
  servlet:
    context-path: /exchange

spring:
  datasource:
    url: jdbc:h2:mem:exchangeDB
    driver-class-name: org.h2.Driver
    username: aquariuxDbOwner
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
url:
  auth-service: